module.exports = [
  "Ein kleiner Strich von dir — und der Tag fühlt sich näher an.",
  "Irgendwo wartet jemand auf deine Farbe.",
  "Heute reicht schon ein Herz auf der Leinwand.",
  "Du musst nichts Großes sagen. Ein Strich genügt.",
  "Zwischen all dem Lärm: ein Moment nur für euch.",
  "Komm kurz vorbei. Die Leinwand vermisst dich.",
  "Liebe braucht oft keinen Text. Nur ein bisschen Farbe.",
  "Ein Tipp. Ein Punkt. Und plötzlich seid ihr wieder nah.",
  "Vielleicht freut sich jemand gerade auf deine Linie.",
  "Nicht laut. Nicht viel. Nur kurz zusammen.",
  "Dein Platz in der Lobby ist noch warm.",
  "Manchmal sagt ein Strich mehr als ein langer Tag.",
  "Wenn du Lust hast — sie sind nur einen Tippen entfernt.",
  "Heute Abend wäre ein gutes Licht zum Malen.",
  "Schön, dass es euch gibt. Die Leinwand auch.",
  "Ein Herz. Ein Moment. Mehr braucht Nähe nicht.",
  "Die Welt ist laut. Eure Lobby kann leise sein.",
  "Falls du jemanden vermisst: malt euch nah.",
  "Eine Linie reicht, um zu sagen: Ich denk an dich.",
  "Eure Farben kennen sich schon.",
  "Kurz rein. Kurz malen. Wieder verbunden.",
  "Die Leinwand wartet geduldig — wie echte Nähe.",
  "Heute: weniger Tippen, mehr Fühlen.",
  "Ein gemeinsamer Strich gegen den Alltag.",
  "Vielleicht fehlt deiner Lobby genau dein Herz.",
  "Nah sein geht auch ohne Worte.",
  "Dein Blau. Ihr Lila. Ein kleines Wir.",
  "Komm zurück — es gibt noch Platz neben dem letzten Strich.",
  "Manchmal ist Liebe einfach: tippen und da sein.",
  "Die Sperrbildschirm-Leinwand vermisst eure Chaos-Herzen.",
  "Ein Punkt von dir. Ein Lächeln bei jemandem.",
  "Heute keine Perfektion. Nur Nähe.",
  "Zeichnen, bis die Stille warm wird.",
  "Eure Lobby ist ein kleiner Ort nur für euch.",
  "Wenn der Tag schwer ist: ein Herz genügt.",
  "Jemand würde sich über deine Farbe freuen.",
  "Nähe ist kein Status. Nähe ist ein Strich.",
  "Lass die Welt draußen. Malt euch rein.",
  "Noch ein kleines Herz — und der Abend wird weicher.",
  "Du musst nicht schreiben. Du kannst malen.",
  "Zwischen Arbeit und To-dos: eine Linie Liebe.",
  "Eure Geschichte braucht keinen Plot. Nur Farbe.",
  "Komm rein, bevor der Moment vergeht.",
  "Ein gemeinsames Gekritzel sagt oft mehr als Sprachnachrichten.",
  "Die Leinwand hält, was der Tag nicht halten kann.",
  "Heute: Softness only.",
  "Vielleicht ist jetzt der richtige Moment für ein Herz.",
  "Dein Nickname. Deine Farbe. Deine Nähe.",
  "Kurz offline von allem — online füreinander.",
  "Malt euch durch den Stress hindurch.",
  "Ein Undo für den Ärger. Ein Strich für die Liebe.",
  "Die Lobby ist still. Bis du kommst.",
  "Schönheit steckt in unperfekten Linien.",
  "Ihr seid näher, als der Bildschirm vermuten lässt.",
  "Ein Tipp — und jemand fühlt sich gesehen.",
  "Heute nicht scrollen. Zeichnen.",
  "Eure Farben dürfen sich wieder berühren.",
  "Manchmal reicht „ich bin da“ als kleiner Kreis.",
  "Die Nacht wird leichter mit einem gemeinsamen Strich.",
  "Komm. Mal. Bleib kurz.",
  "Nähe speichert sich nicht in Chats — eher auf der Leinwand.",
  "Ein Herz für den, der gerade an dich denkt.",
  "Lass uns den Tag weicher malen.",
  "Deine Lobby hat Heimweh nach dir.",
  "Kein Drama. Nur Farbe und Nähe.",
  "Ein Moment zu zweit, mitten im Alltag.",
  "Wenn Worte fehlen, hilft ein Strich.",
  "Heute Abend: wenig Text, viel Herz.",
  "Die Leinwand ist euer stiller Chat.",
  "Komm vorbei — auch fünf Sekunden zählen.",
  "Liebe sieht aus wie eure wirren Linien.",
  "Jemand wartet nicht auf Perfektion. Auf dich.",
  "Ein kleiner Kreis. Ein großes Gefühl.",
  "Zeichnet euch nah, auch wenn ihr weit seid.",
  "Die App ist still. Eure Nähe muss es nicht sein.",
  "Heute: ein Herz, das ankommt.",
  "Zwischen Tür und Alltag — kurz LUV.",
  "Eure Lobby kennt eure Geheimnisse in Farbe.",
  "Ein Strich sagt: Ich bin noch da.",
  "Malen statt Grübeln.",
  "Vielleicht braucht heute jemand genau dein Blau.",
  "Nähe beginnt oft mit einem unscheinbaren Punkt.",
  "Komm rein. Die anderen Farben freuen sich.",
  "Kein Filter. Keine Pose. Nur eure Linien.",
  "Ein gemeinsames Gekritzel gegen die Einsamkeit.",
  "Heute reicht „hier bin ich“ in Farbe.",
  "Die Leinwand ist bereit. Bist du es auch?",
  "Kurz tippen. Lang nachwirken.",
  "Eure Liebe darf chaotisch sein — und bunt.",
  "Ein Herz, das nicht gelöscht werden muss.",
  "Wenn alles zu viel ist: eine ruhige Linie.",
  "Jemand vermisst deine Farbe — auch wenn’s niemand sagt.",
  "Malt euch eine Pause.",
  "Heute: Nähe ohne Stress.",
  "Ein kleiner Besuch in der Lobby verändert den Abend.",
  "Die schönsten Nachrichten sind manchmal Striche.",
  "Komm zurück zu dem, was sich anfühlt wie ihr.",
  "Ein Punkt für dich. Ein Punkt für uns.",
  "Zwischen den Nachrichten: eure Leinwand.",
  "Liebe in Echtzeit — ohne Perfektionsdruck.",
  "Noch ein Herz. Dann fühlt sich alles leichter an.",
  "Die Lobby hält den Platz frei — für dich.",
  "Zeichnen, bis das Lächeln wieder da ist.",
  "Ein gemeinsamer Moment, bevor der Tag endet.",
  "Weniger Screen-Zeit für die Welt. Mehr für euch.",
  "Deine Farbe fehlt im Bild.",
  "Heute Abend wäre ein gutes Licht für Nähe.",
  "Ein Strich. Ein Atemzug. Verbunden.",
  "Die Leinwand wartet nicht auf den richtigen Zeitpunkt — der bist du.",
  "Malt euch gutnacht, wenn Worte müde sind.",
  "Nähe kann so klein beginnen. Und so groß ankommen.",
  "Komm rein. Es darf leicht sein.",
  "Ein Herz auf dem Sperrbildschirm — und die Welt wird weicher.",
  "Eure Linien kennen den kürzesten Weg zueinander.",
  "Heute nicht allein fühlen. Zusammen malen.",
  "Ein kleiner Besuch. Ein großes Ankommen.",
  "Die schönste Push-Nachricht bist du selbst — auf der Leinwand.",
  "Lass uns den Rest des Tages bunt machen.",
  "Irgendwo ist jemand einen Tippen von dir entfernt.",
  "Ein letzter Strich für heute. Oder der erste von vielen.",
  "Komm kurz vorbei."
];
