/** Cozy / süße / leicht lustige Share-Texte für OG-Previews & Einladungen. */
const SHARE_LINES = [
  "Ein Herz auf der Leinwand sagt manchmal mehr als hundert Nachrichten.",
  "Komm kurz vorbei — die Farben vermissen dich schon.",
  "Nur ein Strich. Und plötzlich seid ihr wieder nah.",
  "Heute reicht ein kleines Hi in Pink.",
  "Die Leinwand ist warm. Dein Platz ist frei.",
  "Gemeinsam kritzeln gegen den Alltag.",
  "Ein Moment nur für euch — ohne Lärm, mit Liebe.",
  "Wer braucht schon Worte, wenn es Stifte gibt?",
  "Tipp. Tip. Herz. Fertig. Verbunden.",
  "Kleine Zeichen. Großes Ankommen.",
  "Die schönste Push-Nachricht malt man selbst.",
  "Komm rein, bevor das Herz eifersüchtig wird.",
  "Leise Nähe. Bunte Beweise.",
  "Ein Punkt von dir — und der Tag wird weicher.",
  "Malen statt Tippen. Fühlen statt Scrollen.",
  "Eure Leinwand wartet wie ein offenes Fenster.",
  "Heute Abend: Chaos-Herzen und leise Lächeln.",
  "Ein Strich reicht, um zu sagen: Ich denk an dich.",
  "Nähe zum Mitnehmen. Ohne Koffer.",
  "Zwischen Tür und Alltag — kurz wir.",
  "Die Welt ist laut. Eure Lobby darf flüstern.",
  "Frisch gestrichen: ein Platz neben dir.",
  "Komm, wir machen den Sperrmodus gemütlich.",
  "Zwei Daumen. Eine Leinwand. Ein Wir.",
  "Kein Drama. Nur Farbe und Nähe.",
  "Dein Name fehlt noch im Bild — süß, aber wahr.",
  "Kurzer Besuch. Langer Nachhall im Herz.",
  "Hier darf Nähe unperfekt und bunt sein.",
  "Ein kritzeliges Hallo schlägt jedes Emoji.",
  "Die Leinwand hat Heimweh nach euch.",
  "Lass uns den Tag ein bisschen rosa machen.",
  "Verbunden sein, ohne etwas erklären zu müssen.",
  "Ein Herz. Ein Lachen. Ein gemeinsamer Moment.",
  "Heute: weniger Chat, mehr Strich.",
  "Komm zeichnen — die Pixel sind schon aufgeregt.",
  "Liebe in Echtzeit, ganz ohne Perfektionsdruck.",
  "Ein kleines Hi, das sich wie Zuhause anfühlt.",
  "Malt euch nah, wenn Worte müde sind.",
  "Die schönsten Geheimnisse sind bunt.",
  "Ein Tipp von dir — und irgendwo lächelt jemand.",
  "Leinwand an, Alltag aus.",
  "Für Herzen, die denselben Bildschirm teilen wollen.",
  "Kurz rein. Kurz malen. Wieder warm.",
  "Hier darf Nähe so klein sein wie ein Punkt.",
  "Ein gemeinsamer Strich gegen den grauen Tag.",
  "Die Einladung ist soft. Das Gefühl nicht.",
  "Komm, wir füllen die Stille mit Farbe.",
  "Kein Meeting. Nur ein Moment für euch.",
  "Dein Platz neben dem letzten Herzchen ist noch frei.",
  "Süße Spoiler: es wird gemütlich.",
  "Ein bisschen Chaos, ein bisschen Liebe, viel wir.",
  "Die Leinwand flüstert: Komm doch.",
  "Nähe speichert sich hier besser als in Chats.",
  "Ein Strich genügt — der Rest ist Gefühl.",
  "Heute malen wir uns ein Lächeln.",
  "Für alle, die „ich denk an dich“ lieber zeichnen.",
  "Warm. Nah. Und ein kleines bisschen albern.",
  "Die Farben kennen sich schon. Du fehlst noch.",
  "Einladen zum Kuscheln — digital, aber echt.",
  "Komm vorbei, bevor das Herz alleine kritzelt.",
  "Kleine Kunst. Große Nähe.",
  "Ein gemeinsames Bild sagt: Du bist nicht allein.",
  "Hier ist Platz für euer leises Wir.",
  "Tipp dich rein — die Leinwand macht den Rest.",
  "Süße Sabotage des Alltags. Mit Stiften.",
  "Ein Herzchen später fühlt sich alles leichter an.",
  "Die schönste Verbindung braucht keinen langen Text.",
  "Malen bis das Lächeln wieder da ist.",
  "Ein Moment, der sich anfühlt wie Hand halten.",
  "Komm, wir machen Nähe sichtbar.",
  "Für Partner:innen, Familie und Herzenschaos.",
  "Die Leinwand hat schon Platz für euch freigehalten.",
  "Ein kritzeliges Date. Ohne Reservierung.",
  "Heute reicht Nähe in zwei Farben.",
  "Lass uns den Rest des Tages weicher machen.",
  "Ein Hi, das bleibt — auf der Leinwand.",
  "Kein Scrollen. Nur Ankommen.",
  "Die Einladung ist kurz. Das Gefühl darf groß sein.",
  "Komm zeichnen, bevor die Sterne eifersüchtig werden.",
  "Hier darf Liebe leise und bunt sein.",
  "Ein gemeinsamer Punkt gegen die Distanz.",
  "Süß, simpel, und ein bisschen magisch.",
  "Die Pixel warten auf euer kleines Chaos.",
  "Ein Strich von dir. Ein Lächeln bei mir.",
  "Nähe zum Aufklappen — direkt auf dem Screen.",
  "Für Momente, die keine große Rede brauchen.",
  "Komm rein. Es darf leicht sein.",
  "Ein Herz auf dem Weg zu dir.",
  "Die Lobby ist gemütlich. Fehlt nur du.",
  "Malen, bis die Entfernung kleiner wird.",
  "Ein kleines Wir gegen den großen Tag.",
  "Hier trifft Nähe auf Farbe — und gewinnt.",
  "Kurzer Link. Langer Gänsehaut-Moment.",
  "Die schönste Nachricht hat heute keine Buchstaben.",
  "Komm, wir schreiben Nähe in Linien.",
  "Ein bisschen Albernheit inklusive.",
  "Für Herzen, die lieber gemeinsam kritzeln.",
  "Die Leinwand sagt hallo. Magst du antworten?",
  "Ein Moment nur für euch — cozy und klar.",
  "Tippen. Verbinden. Nah sein.",
  "Liebe in Linien. Nähe in Echtzeit.",
  "Ein letztes Herzchen für den Weg zu dir.",
];

function pickShareLine() {
  if (!SHARE_LINES.length) return "Ein kleiner Moment nur für euch.";
  return SHARE_LINES[Math.floor(Math.random() * SHARE_LINES.length)];
}

module.exports = { SHARE_LINES, pickShareLine };
